# Generated by Django 5.0.4 on 2024-04-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='proteinsConsumed',
            field=models.FloatField(default=0),
        ),
    ]
