# Generated by Django 5.0.4 on 2024-04-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MemberInfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberinfo',
            old_name='memberid',
            new_name='member',
        ),
    ]
