# Generated by Django 5.0.4 on 2024-04-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MemberInfo', '0002_rename_memberid_memberinfo_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberinfo',
            old_name='member',
            new_name='memberid',
        ),
    ]
